// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSV5LYuiWnh34Gg3XlwTreqvyxve6nZUs',
    appId: '1:478726029119:web:0340defb29e9379a3fdd8a',
    messagingSenderId: '478726029119',
    projectId: 'flutter-chat-app-3410a',
    authDomain: 'flutter-chat-app-3410a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3410a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ3XHvcNubaS822qfs4yHivipMGdObH9I',
    appId: '1:478726029119:android:1a46c3d3137beba63fdd8a',
    messagingSenderId: '478726029119',
    projectId: 'flutter-chat-app-3410a',
    storageBucket: 'flutter-chat-app-3410a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2Sy06iI7UPZzD4mEuf7fNDPyO9u46gs',
    appId: '1:478726029119:ios:5c3e2517762856b33fdd8a',
    messagingSenderId: '478726029119',
    projectId: 'flutter-chat-app-3410a',
    storageBucket: 'flutter-chat-app-3410a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO2Sy06iI7UPZzD4mEuf7fNDPyO9u46gs',
    appId: '1:478726029119:ios:f48e71a20f7ac4323fdd8a',
    messagingSenderId: '478726029119',
    projectId: 'flutter-chat-app-3410a',
    storageBucket: 'flutter-chat-app-3410a.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
